[package]
name = "parseable-lambda-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive", "env"] }
lambda-extension = "0.8.0"
once_cell = "1.17.0"
tokio = { version = "1.24.2", features = ["rt-multi-thread"] }
tokio-macros = "1.8.2"
